/*

// 1.Part A: Student–Enrollment Relationship

SELECT S.STUDENT_ID, S.STUDENT_NAME, E.COURSE_ID
FROM Student S
INNER JOIN Enrollment E
ON S.STUDENT_ID = E.STUDENT_ID;

SELECT S.STUDENT_NAME, E.SEMESTER
FROM Student S
INNER JOIN Enrollment E
ON S.STUDENT_ID = E.STUDENT_ID;

SELECT S.STUDENT_NAME, E.GRADE
FROM Student S
INNER JOIN Enrollment E
ON S.STUDENT_ID = E.STUDENT_ID;



// 2. Part B: Course–Faculty Relationship

SELECT C.COURSE_NAME, C.CREDITS, F.FACULTY_NAME
FROM COURSE C
INNER JOIN FACULTY F
ON C.FACULTY_ID = F.FACULTY_ID;

SELECT C.COURSE_NAME
FROM COURSE C
INNER JOIN FACULTY F
ON C.FACULTY_ID = F.FACULTY_ID
WHERE F.FACULTY_ID = 'F201';

SELECT F.FACULTY_NAME, F.DESIGNATION, C.COURSE_NAME
FROM FACULTY F
INNER JOIN COURSE C
ON F.FACULTY_ID = C.FACULTY_ID;



// 3 Part C: Student–Course–Enrollment Relationship

SELECT S.STUDENT_NAME, C.COURSE_NAME
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID;


SELECT S.STUDENT_NAME, C.COURSE_NAME, E.SEMESTER
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID;


SELECT S.STUDENT_NAME, C.COURSE_NAME, E.GRADE
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID
WHERE E.SEMESTER = 4;

SELECT C.COURSE_NAME
FROM ENROLLMENT E
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID
WHERE E.STUDENT_ID = 'S401';


// 4. PART D Department JOIN


SELECT S.STUDENT_NAME, S.DEPT_ID, C.COURSE_NAME
FROM STUDENT S
INNER JOIN COURSE C
ON S.DEPT_ID = C.DEPT_ID;

SELECT D.DEPT_NAME, C.COURSE_NAME
FROM DEPARTMENT D
INNER JOIN COURSE C
ON D.DEPT_ID = C.DEPT_ID;

SELECT F.FACULTY_NAME, D.DEPT_NAME
FROM FACULTY F
INNER JOIN DEPARTMENT D
ON F.DEPT_ID = D.DEPT_ID;


// 5 Part E: Filtering & Sorting

SELECT S.STUDENT_NAME, C.COURSE_NAME
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID
WHERE S.DEPT_ID = 'D01';

SELECT S.STUDENT_NAME, C.COURSE_NAME
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID
ORDER BY S.STUDENT_NAME ASC;

SELECT F.FACULTY_NAME, C.COURSE_NAME
FROM FACULTY F
INNER JOIN COURSE C
ON F.FACULTY_ID = C.FACULTY_ID
ORDER BY C.CREDITS DESC;



// 6 Part F: Analytical JOIN

SELECT C.COURSE_NAME, COUNT(E.STUDENT_ID) AS TOTAL_STUDENTS
FROM COURSE C
INNER JOIN ENROLLMENT E
ON C.COURSE_ID = E.COURSE_ID
GROUP BY C.COURSE_NAME;

SELECT F.FACULTY_NAME, COUNT(C.COURSE_ID) AS TOTAL_COURSES
FROM FACULTY F
INNER JOIN COURSE C
ON F.FACULTY_ID = C.FACULTY_ID
GROUP BY F.FACULTY_NAME;

SELECT D.DEPT_NAME, COUNT(S.STUDENT_ID) AS TOTAL_STUDENTS
FROM DEPARTMENT D
INNER JOIN STUDENT S
ON D.DEPT_ID = S.DEPT_ID
GROUP BY D.DEPT_NAME;

SELECT C.COURSE_NAME, MAX(E.GRADE) AS MAX_GRADE
FROM COURSE C
INNER JOIN ENROLLMENT E
ON C.COURSE_ID = E.COURSE_ID
GROUP BY C.COURSE_NAME;

*/