
--Basic Subqueries

SELECT STUDENT_NAME
FROM STUDENT
WHERE DEPT_ID = (
    SELECT DEPT_ID
    FROM STUDENT
    WHERE STUDENT_ID = 'S401'
);

SELECT STUDENT_NAME
FROM STUDENT
WHERE GENDER = (
    SELECT GENDER
    FROM STUDENT
    WHERE STUDENT_ID = 'S402'
);

SELECT STUDENT_NAME
FROM STUDENT
WHERE DEPT_ID = (
    SELECT DEPT_ID
    FROM STUDENT
    WHERE STUDENT_ID = 'S403'
);

--Subqueries with IN

SELECT STUDENT_NAME
FROM STUDENT
WHERE DEPT_ID IN (
    SELECT DEPT_ID
    FROM STUDENT
    WHERE GENDER = 'F'
);

SELECT STUDENT_NAME
FROM STUDENT
WHERE STUDENT_ID IN (
    SELECT STUDENT_ID
    FROM ENROLLMENT
);


SELECT STUDENT_NAME
FROM STUDENT S
WHERE EXISTS (
    SELECT *
    FROM ENROLLMENT E
    WHERE S.STUDENT_ID = E.STUDENT_ID
);


--Aggregate Subqueries

SELECT COURSE_NAME
FROM COURSE
WHERE CREDITS > (
    SELECT AVG(CREDITS)
    FROM COURSE
);

SELECT STUDENT_NAME
FROM STUDENT
WHERE TO_NUMBER(SUBSTR(STUDENT_ID, 2)) > (
    SELECT AVG(TO_NUMBER(SUBSTR(STUDENT_ID, 2)))
    FROM STUDENT
);

SELECT DEPT_ID
FROM STUDENT
GROUP BY DEPT_ID
HAVING COUNT(*) > (
    SELECT AVG(cnt)
    FROM (
        SELECT COUNT(*) cnt
        FROM STUDENT
        GROUP BY DEPT_ID
    )
);

--Subqueries Instead of JOIN

SELECT STUDENT_NAME
FROM STUDENT
WHERE STUDENT_ID IN (
    SELECT STUDENT_ID
    FROM ENROLLMENT
);

SELECT STUDENT_NAME
FROM STUDENT
WHERE DEPT_ID IS NOT NULL;

SELECT COURSE_NAME
FROM COURSE
WHERE COURSE_ID IN (
    SELECT COURSE_ID
    FROM ENROLLMENT
);

--Analytical Subqueries

SELECT COURSE_NAME
FROM COURSE
WHERE CREDITS = (
    SELECT MAX(CREDITS)
    FROM COURSE
);

SELECT STUDENT_NAME
FROM STUDENT
WHERE STUDENT_ID IN (
    SELECT STUDENT_ID
    FROM ENROLLMENT
    GROUP BY STUDENT_ID
    HAVING COUNT(*) > 1
);

SELECT DEPT_ID
FROM STUDENT
GROUP BY DEPT_ID
HAVING COUNT(*) = (
    SELECT MAX(cnt)
    FROM (
        SELECT COUNT(*) cnt
        FROM STUDENT
        GROUP BY DEPT_ID
    )
);


--Challenging Questions

SELECT STUDENT_NAME
FROM STUDENT
WHERE STUDENT_ID IN (
    SELECT STUDENT_ID
    FROM ENROLLMENT
    WHERE COURSE_ID IN (
        SELECT COURSE_ID
        FROM ENROLLMENT
        WHERE STUDENT_ID = 'S401'
    )
);

SELECT STUDENT_NAME
FROM STUDENT
WHERE STUDENT_ID NOT IN (
    SELECT STUDENT_ID
    FROM ENROLLMENT
);

SELECT COURSE_NAME
FROM COURSE
WHERE COURSE_ID NOT IN (
    SELECT COURSE_ID
    FROM ENROLLMENT
);
